### ISSUE TITLE
this repo doesn't seems right

### ISSUE THREAD

**Issue by rsharifnasab** [radinshayanfar/testrepo#1]
hi radin,
it seems you just created this repository for testing, if your test is done, **please delete it.**
thank you!

**Comment by radinshayanfar** [comment]
Thanks for your contribution.
But I think **someone** who **starred** this repository liked it and doesn't like this repository to be deleted.

**Comment by radinshayanfar** [comment]
> 
> 
> hi radin,
> it seems you just created this repository for testing, if your test is done, **please delete it.**
> thank you!

Thanks for your contribution.
But I think **someone** who **starred** this repository liked it and doesn't like this repository to be deleted.

**Comment by rsharifnasab** [comment]
yes, maybe you are right, so i close this issue.
thank you for your fast response.
